export const types = {
  FETCH_STORIES: 'stories/FETCH_STORIES',
  FETCH_STORIES_SUCCESS: 'stories/FETCH_STORIES_SUCCESS',

  FETCH_PAGE_STORIES: 'stories/FETCH_PAGE_STORIES',

  FETCH_STORY_INFO_SUCCESS: 'stories/FETCH_STORY_INFO_SUCCESS',

  SET_CURRENT_STORIES: 'stories/SET_CURRENT_STORIES',

  FETCH_AUTHOR_INFO: 'stories/FETCH_AUTHOR_INFO',
  FETCH_AUTHOR_INFO_SUCCESS: 'stories/FETCH_AUTHOR_INFO_SUCCESS',

  SET_CURRENT_AUTHOR: 'stories/SET_CURRENT_AUTHOR',

  SET_PAGE: 'stories/SET_PAGE',

  SET_LOADER: 'stories/SET_LOADER'
}
